'''
389. Find the Difference
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        '''
        Similar to 136. Single Number
        '''
        A = ord('a')
        bit = 0
        
        for e in s:
            bit = bit ^ (ord(e) - A)
        for e in t:
            bit = bit ^ (ord(e) - A)
            
        return chr(bit + A)
